job:
  - name: job1
    config:
      min_replicas: 1
      max_replicas: 5
      entry_point: "uv run {{ cookiecutter.module_name }}/run.py"
      namespace: app_ns
  - name: job2
    config:
      min_replicas: 2
      max_replicas: 10
      entry_point: "uv run {{ cookiecutter.module_name }}/another_run.py"
      namespace: another_ns